server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/onlineshop
    username: postgres
    password: r0887970905
    maximumPoolSize: 15
    hikari:

    jpa:
      show_sql: true
      format_sql: true
      database-platform: org.hibernate.dialect.PostgreSQL94Dialect